apiVersion: v1
kind: Pod
metadata:
  name: gan-pytorch
  labels: 
     name: post-gan
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: alpha.kubernetes.io/nvidia-gpu-name
            operator: In
            values:
            - 1080Ti
  containers:
  - args:
    - echo 'hello';sleep 20d; true
    command:
    - /bin/bash
    - -c
    image: harbor.ail.unisound.com/zhanghui/pytorch-v0.2:latest
    ports: 
    - containerPort: 6006
      protocol: TCP
    imagePullPolicy: Always 
    name: gan-cpu 
    volumeMounts:
    - mountPath: /gfs
      name: nfs0
    - mountPath: '/tmp'
      name: tmp 
    - mountPath: '/lustre'
      name: lustre 
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  terminationGracePeriodSeconds: 1
  volumes:
  - name: nfs0
    nfs:
      path: "/volume1/gfs"
      server: 10.10.10.251
      readOnly: false
  - hostPath:
      path: /tmp
    name: tmp 
  - hostPath:
      path: /lustre
    name: lustre
